version: "3.0"
services:
    postgres:
        container_name: db_postgres
        image: postgres:16
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        networks:
            - custom
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
                ]
            interval: 10s
            timeout: 3s
            retries: 3
        volumes:
            - db-data:/var/lib/postgresql

    pgadmin:
        container_name: db_pgadmin4
        image: dpage/pgadmin4
        restart: always
        ports:
            - "5050:80"
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        networks:
            - custom
        volumes:
            - db-pgadmin-data:/var/lib/pgadmin
networks:
    custom:
        driver: bridge

volumes:
    db-pgadmin-data:
    db-data:
